version: '3.4'

services:
  master:
    build:
      context: base
      target: master
  ps4:
    build: base
    links:
      - master:master
    command: m2_ps4 ps4_to_msg.py enable_led_thread:=true dev:=input/js0
