version: '3.4'

services:
  master:
    build:
      context: base
      target: master
  joy:
    build: base
    devices:
      - /dev/input/js0
    links:
      - master:master
    command: joy joy_node dev:=/dev/input/js0
  ps4:
    build: base
    devices:
      - /dev/input/js0
    links:
      - master:master
    command: m2_ps4 ps4_to_msg.py dev:=/dev/input/js0
    privileged: true
  foo:
    build:
      context: base
      target: catkin-remake
    links:
      - master:master
    volumes:
      - ./foo:/src/foo:ro
    command: foo talker.py
