name: run

on:
  push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose build
      - run: docker-compose up -d
      - run: sleep 5
      - run: docker-compose logs
